# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: ozonmp/srv_verification_api/v1/srv_verification_api.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import validate.validate_pb2
import google.api.annotations_pb2
import google.protobuf.timestamp_pb2
import ozonmp.srv_verification_api.v1.srv_verification_api_pb2


class SrvVerificationApiServiceBase(abc.ABC):

    @abc.abstractmethod
    async def DescribeVerificationV1(self, stream: 'grpclib.server.Stream[ozonmp.srv_verification_api.v1.srv_verification_api_pb2.DescribeVerificationV1Request, ozonmp.srv_verification_api.v1.srv_verification_api_pb2.DescribeVerificationV1Response]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/ozonmp.srv_verification_api.v1.SrvVerificationApiService/DescribeVerificationV1': grpclib.const.Handler(
                self.DescribeVerificationV1,
                grpclib.const.Cardinality.UNARY_UNARY,
                ozonmp.srv_verification_api.v1.srv_verification_api_pb2.DescribeVerificationV1Request,
                ozonmp.srv_verification_api.v1.srv_verification_api_pb2.DescribeVerificationV1Response,
            ),
        }


class SrvVerificationApiServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.DescribeVerificationV1 = grpclib.client.UnaryUnaryMethod(
            channel,
            '/ozonmp.srv_verification_api.v1.SrvVerificationApiService/DescribeVerificationV1',
            ozonmp.srv_verification_api.v1.srv_verification_api_pb2.DescribeVerificationV1Request,
            ozonmp.srv_verification_api.v1.srv_verification_api_pb2.DescribeVerificationV1Response,
        )
